### PR TITLE
Fix application ID parsing, etc.

### PR DESCRIPTION
**Pull request by billyeh**
- Take out some old merge markers that messed up the code
- More complete null and empty string-checking for locations
- Check for id in 'application_number' or 'application_reference', in old and new schemas, respectively.

### CODE REVIEW

**Comment by billyeh** [comment]
By the way, integration tests have gone a little crazy since the last changes with this celery thing, and I'm looking into it now because I also wanted to add more for all 13 years of application schemas just to be safe. I'll keep the repo updated with new pull requests/issues when I find them.

**Comment by gtfierro** [comment]
I removed the external celery stuff, so now it all runs in a single thread. I'll hack on it today and let you know if anything needs to be changed.

**Comment by billyeh** [comment]
It also seems like we'll need to change application ID parsing for grants and/or applications, since they have the same information, just in slightly different formats, right now. I can change the applications' stuff because it seems like having [year]/id is redundant, and grants just have the id.

**Comment by gtfierro** [comment]
Can you make the necessary changes in the grant/application parsers so that we get the IDs and numbers as they appear in usptofixed.application and application.application? We need to change usptofixed.application.id, application.application.number and application.application.id

**Comment by billyeh** [comment]
Yup - I'll add to this pull request later this week.

**Comment by gtfierro** [comment]
I promise I'll look into merging this PR this week, Bill

**Comment by billyeh** [comment]
Sure, whenever you have time. Don't forget that in this pull request, the application `id` is still in the form "year/8-digit serial number", and the `number` is in the form "8-digit serial number".

**Comment by gtfierro** [comment]
Isn't that what we decided on using?

**Comment by gtfierro** [comment]
As in, that's what it's like in the current usptofixed/apptest database?

**Comment by billyeh** [comment]
Yup, exactly. Sorry, just wanted to clarify.

**Comment by billyeh** [comment]
I don't even know if this helps, but I've rebased so that if there's merge conflicts you don't have to fix them for the pull request.  There was also a typo on a `print` and we might want to add a dependency for `joblib`.

**Comment by gtfierro** [comment]
Thanks for the rebase, Bill.  I have a few changes in my own branch that I want to push in order to finish the contract. I'll be doing that sometime soon, and then I'll ping you so you can do a final rebase and then we'll merge in the PR. Sound good?

**Comment by billyeh** [comment]
Of course. Thanks for the reply! When things are stable I'll be able to add tests too :)

**Comment by billyeh** [comment]
Thanks for merging. Will close! :+1:

**Pull request closed without merging**
