### PR TITLE
sqlalchemy readme

### PR DESCRIPTION
**Pull request by laironald**
i've made the readme file cleaner. this file can be integrated with the root readme, if appropriate.

### CODE REVIEW

**Comment by gtfierro** [comment]
Can you run the `fetch upstream` and `merge upstream/sqlalchemy` commands before submitting the pull request? Github is warning me that this can't be automatically merged, which means we probably edited the same chunk of code. I don't want to accidentally remove your changes in resolving the conflict.

**Comment by laironald** [comment]
sure. +that. i'll also work on the integration test bit.

**Comment by laironald** [comment]
added the new integration files and ran it. integration tests pass.
I do see a bit of a strange error

```
make: Warning: File `Makefile' has modification time 8.3e+02 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
```

not sure if that was there before or not

**Comment by gtfierro** [comment]
That error continues to confound me to this day. It's not a serious error. Try running `touch` on the file?

**Comment by laironald** [comment]
uh ok. its a warning msg not a big deal.

On Wed, Aug 14, 2013 at 8:05 PM, Gabe Fierro notifications@github.comwrote:

> That error continues to confound me to this day. It's not a serious error.
> Try running touch on the file?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/funginstitute/patentprocessor/pull/52#issuecomment-22682524
> .

## 

sent from mobile

**Pull request merged**
