### PR TITLE
Removed a lot of obsolete references to zipcodes.

### PR DESCRIPTION
**Pull request by Vadskye**
I had a suspicion that trying to match zipcode information could be causing some problems. The output should only be marginally changed: there is still a zipcode column, but it now contains an empty string instead of 0 because 0 could be construed as being meaningful.

### CODE REVIEW

**Comment by gtfierro** [comment]
I'm getting the following error on the unittests:

```
Processing test_geocode_replace_loc.py file..
...F............
======================================================================
FAIL: test_domestic_first3_jaro_winkler_sql (__main__.TestGeocodeReplaceLoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_geocode_replace_loc.py", line 50, in test_domestic_first3_jaro_winkler_sql
    self.assertTrue('LOGAN'==element,"{0} should be {1}".format(element,'LOGAN'))
AssertionError: UT should be LOGAN

----------------------------------------------------------------------
Ran 16 tests in 8.115s

FAILED (failures=1)
domestic_2nd_layer_sql
domestic_block_remove_sql
domestic_first3_2nd_jaro_winkler_sql
domestic_first3_jaro_winkler_sql
domestic_last4_jaro_winkler_sql
domestic_sql
domestic_sql
foreign_block_split_sql
foreign_first3_2nd_jaro_winkler_sql
foreign_first3_jaro_winkler_sql
foreign_full_name_1_sql
foreign_full_name_2_sql
foreign_full_name_2nd_layer_sql
foreign_full_nd_2nd_layer_sql
foreign_last4_jaro_winkler_sql
foreign_no_space_2nd_layer_sql
foreign_short_form_sql
Processing test_geocode_setup.py file..
F..
======================================================================
FAIL: test_create_usloc_table (__main__.TestGeocodeSetup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_geocode_setup.py", line 61, in test_create_usloc_table
    self.assertTrue(0 == element, "{0} should be {1}".format(element,0))
AssertionError:  should be 0

----------------------------------------------------------------------
Ran 3 tests in 1.605s

FAILED (failures=1)
```

**Comment by Vadskye** [comment]
Dang it. I fixed those, but I forgot to commit. A pull request be coming
your way very soon.

**Comment by gtfierro** [comment]
Thanks! Should I just close this pull request without merging, then?

**Comment by Vadskye** [comment]
Sure. Not really sure how that will work, but it sounds like it would be
easiest.

**Comment by gtfierro** [comment]
Well, submit another pull request when you fix the issue, and we'll figure it out.

---

Gabe Fierro

**Pull request closed without merging**
